### PR TITLE
Add button to toggle (unlock) yubikey to indicator applet

### PR DESCRIPTION
**Pull request by mozfreddyb**
@bfelder What do you think?
One could rename "Toggle" to "Unlock" of course.

(This patch /might/ not cleanly apply, if you take my other pull request)

### CODE REVIEW

**Review by pykong — COMMENTED** [review]
Are your changes supposed to toggle in the true meaning of that word == switch YubiGuard ON/OFF?

Or should YubiGuard be triggered in the same way you would do via key combination?

**Comment by mozfreddyb** [comment]
I'm only unlocking, similar to the key combo. It's even doing the exact same thing. Calling the file with the `-t` param.

Should I rename things to "unlock"?

**Comment by mozfreddyb** [comment]
> Should I rename things to "unlock"?
I just did that.

**Comment by pykong** [comment]
The toggle should be 'unclickable' during unlock and become 'clickable' after lock again.
(See the logic which changes the icon to know how to do it.)

It is inelegant calling the script again via subprocess. There should be a method call here.

**Comment by mozfreddyb** [comment]
> The toggle should be 'unclickable' during unlock and become 'clickable' after lock again. (See the logic which changes the icon to know how to do it.)

Good point. I will do that when I have an impression on how to change the state without calling the script again (see below)

> It is inelegant calling the script again via subprocess. There should be a method call here.

True, but calling change_state on the YubiGuard class somehow did not work. I assumed it was a problem with things happening in different threads and I couldn't figure that out. Any pointers?

**Comment by pykong** [comment]
Unlock will now be triggered via Zmq directly.
Actually it would have been most elegant to use the inbuilt queue for that purpose. I will check whether I can do that.

I have also marked the respective lines that should hold activate/deactivate commands for the button you added.

**Comment by pykong** [comment]
I have now wired the button to respective queue. It should now also activate/deactivate when unlocked/locked. I have not tested this commit yet.

You may do that. Give me a feedback so I can merge into the main branch.

**Comment by mozfreddyb** [comment]
Wow, I was expecting just a few pointers, but your commits helped me understand how things work.
The `Unlock` item is now correctly disabled, except when there's no YubiKey found. I don't know why update_icon isn't called in that case. Will possibly take a look later

**Comment by pykong** [comment]
Have you fixed the issue of not-updating logo?
I like to merge into the major branch.

And do not forget to STAR YubiGuard!
I would appreciate it! THX!

**Comment by mozfreddyb** [comment]
What's still left is that the "Unlock" menu item does not automatically lock if you remove the Yubikey. I couldn't figure out why the https://github.com/bfelder/YubiGuard/pull/6/files#diff-0da1838ca3c4eb687e8a6d41b6b87856R162 branch is never called.

**Comment by pykong** [comment]
OK. fixed that. Two little lines only. It works perfectly now. Tell me your opinion. If you find everything to be OK, I am going to merge into the major brand.

**Comment by mozfreddyb** [comment]
looks good, thanks 👍

**Comment by pykong** [comment]
Merged. Was a pleasure working with you. Just get in touch in case you need anything in the future...

**Comment by mozfreddyb** [comment]
Thank you. Belated happy holidays 🎆 🎉

**Pull request merged**
